import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, Any, List
from sqlalchemy import text
from sqlalchemy.orm import Session
from ..config import settings

logger = logging.getLogger(__name__)

def send_email_notification(recipient_email: str, subject: str, body_html: str) -> Dict[str, Any]:
    if not settings.smtp_server or not settings.smtp_email:
        return {"status": 500, "message": "Konfigurasi SMTP tidak lengkap di environment variables (.env)"}

    try:
        msg = MIMEMultipart()
        msg['From'] = settings.smtp_email
        msg['To'] = recipient_email
        msg['Subject'] = subject
        msg.attach(MIMEText(body_html, 'html'))

        server = smtplib.SMTP(settings.smtp_server, settings.smtp_port, timeout=10)
        server.starttls()
        server.login(settings.smtp_email, settings.smtp_password)
        server.send_message(msg)
        server.quit()
        return {"status": 200, "message": "Email sent successfully"}
    except Exception as e:
        logger.error(f"Email failed to {recipient_email}: {e}")
        return {"status": 500, "message": f"Email failed: {str(e)}"}

def get_registered_emails(db: Session) -> List[str]:
    """Mengambil daftar semua email unik dari tabel presales."""
    try:
        query = text("SELECT DISTINCT email FROM presales WHERE email IS NOT NULL AND email != '' ORDER BY email")
        result = db.execute(query).fetchall()
        return [row[0] for row in result]
    except Exception as e:
        logger.error(f"Error fetching emails: {e}")
        return []

def check_and_remind_inactive_presales(db: Session, target_email: str = "krisa.kurniawan@sisindokom.com") -> Dict[str, Any]:
    """
    Mengecek presales yang tidak memiliki aktivitas > 14 hari atau tidak pernah beraktivitas sama sekali.
    Lalu mengirimkan email rekap.
    """
    try:
        query = text("""
            SELECT 
                p.presales_name, 
                p.email,
                MAX(a.timestamp) as last_activity
            FROM presales p
            LEFT JOIN activity_logs a ON p.presales_name = a.user_name
            GROUP BY p.presales_name, p.email
            HAVING MAX(a.timestamp) < NOW() - INTERVAL '14 days'
               OR MAX(a.timestamp) IS NULL
            ORDER BY last_activity ASC NULLS FIRST
        """)
        
        result = db.execute(query).mappings().fetchall()
        inactive_users = [dict(row) for row in result]
        
        if not inactive_users:
            return {"status": 200, "message": "Semua Presales aktif dalam 14 hari terakhir. Aman! ✅"}

        list_html = ""
        for user in inactive_users:
            if user['last_activity'] is not None:
                last_date = user['last_activity'].strftime('%d %B %Y')
            else:
                last_date = "Belum ada aktivitas sama sekali"
            
            list_html += f"<li><b>{user['presales_name']}</b> - Last Activity: <span style='color:red;'>{last_date}</span></li>"

        email_body = f"""
        <h3>🚨 Presales Inactivity Alert (> 14 Hari)</h3>
        <p>Halo,</p>
        <p>Sistem mendeteksi ada beberapa akun Presales yang <b>tidak melakukan aktivitas (input/update opportunity) selama lebih dari 14 hari</b> di Presales App.</p>
        <p>Berikut adalah daftarnya:</p>
        <ul>
            {list_html}
        </ul>
        <p><b>Action Required:</b></p>
        <p>Mohon untuk melakukan <i>follow-up</i> kepada nama-nama di atas.</p>
        <br>
        <p style='font-size: 10px; color: grey;'>System Auto-Generated by Presales API</p>
        """

        res_email = send_email_notification(target_email, "[ACTION REQUIRED] Inactive Presales Report", email_body)

        if res_email['status'] == 200:
            return {"status": 200, "message": f"Reminder terkirim ke {target_email}! Ditemukan {len(inactive_users)} presales tidak aktif."}
        else:
            pesan_error_asli = res_email.get('message', 'Unknown Error')
            return {"status": 500, "message": f"Gagal mengirim email: {pesan_error_asli}"}

    except Exception as e:
        logger.error(f"Error in inactive reminder: {str(e)}")
        return {"status": 500, "message": f"Database Error: {str(e)}"}
