[connections.postgresql]
dialect = "postgresql"
host = "36.67.62.245"
port = 8088
database = "dbpresales"
username = "admin"
password = "bzftDFqgCxGg0gQ"

[smtp]
server = "smtp.office365.com" 
port = 587
email = "krisa.kurniawan@sisindokom.com"
password = "gvnjsvczybjljvnx"